import type { Metadata } from 'next';
import { IBM_Plex_Sans_KR } from 'next/font/google';
import './globals.css';

const ibmPlexSansKr = IBM_Plex_Sans_KR({
  variable: '--font-ibm-flex-sans-kr',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export interface RootProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSansKr.variable} font-sansKr antialiased`}>
        {children}
      </body>
    </html>
  );
}
